-- Generated by TypeScript Script for News

-- Languages table pre-populated as per schema
INSERT OR IGNORE INTO languages (code, name, is_default) VALUES ('en', 'English', FALSE), ('ja', 'Japanese', TRUE);

-- Inserting News Categories
INSERT OR IGNORE INTO categories (id, type) VALUES (300, 'news');
INSERT OR IGNORE INTO category_translations (category_id, language_code, category_name) VALUES (300, 'ja', 'お知らせ');
INSERT OR IGNORE INTO categories (id, type) VALUES (301, 'news');
INSERT OR IGNORE INTO category_translations (category_id, language_code, category_name) VALUES (301, 'ja', 'その他');
INSERT OR IGNORE INTO categories (id, type) VALUES (302, 'news');
INSERT OR IGNORE INTO category_translations (category_id, language_code, category_name) VALUES (302, 'ja', '研究開発');

IGNORE