import { parse } from "csv-parse/sync";
import * as fs from "fs";
import * as path from "path";

// --- TYPE DEFINITIONS (matching the database schema) ---

interface Category {
  id: number;
  type: "equipments";
}

interface CategoryTranslation {
  category_id: number;
  language_code: "ja" | "en";
  category_name: string;
}

interface Post {
  id: number;
  type: "equipments";
  category: string; // The name of the category
  thumbnail: string;
}

interface ContentSection {
  type: "html";
  content: string;
}

interface PostTranslation {
  post_id: number;
  language_code: "ja" | "en";
  title: string;
  cardDescription: string;
  sections: ContentSection[];
}

// --- CSV ROW INTERFACE ---

interface CsvRow {
  ID: string;
  Title: string;
  Content: string;
  Excerpt: string;
  "Post Type": string;
  "Image URL": string;
  _locale: string;
  _original_post: string;
  Status: string;
}

// --- UTILITY FUNCTIONS ---

/**
 * Escapes a string for use in an SQL single-quoted literal.
 */
const escapeSqlString = (value: string | null | undefined): string => {
  if (value === null || value === undefined) {
    return "NULL";
  }
  return `'${value.replace(/'/g, "''")}'`;
};

/**
 * Extracts the first image URL from the pipe-separated string.
 */
const getThumbnailUrl = (imageUrlField: string | undefined): string => {
  if (!imageUrlField) return "";
  return imageUrlField.split("|")[0] || "";
};

/**
 * Creates a short description from the main content.
 */
const createCardDescription = (content: string | undefined): string => {
  if (!content) return "";
  // Remove HTML tags and extra whitespace, then truncate.
  const plainText = content
    .replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return plainText.length > 150
    ? plainText.substring(0, 147) + "..."
    : plainText;
};

// --- MAIN LOGIC ---

/**
 * Main function to process the CSV and generate the SQL file.
 */
const generateEquipmentSqlScript = () => {
  const csvFilePath = path.join(__dirname, "保有技術・設備_all.csv");
  if (!fs.existsSync(csvFilePath)) {
    console.error(`Error: The file ${csvFilePath} was not found.`);
    return;
  }
  const fileContent = fs.readFileSync(csvFilePath, { encoding: "utf-8" });

  // Parse the CSV content
  const records: CsvRow[] = parse(fileContent, {
    columns: true,
    skip_empty_lines: true,
  });

  // Filter for relevant posts (published equipments)
  const publishedEquipments = records.filter(
    (row) => row.Status === "publish" && row["Post Type"] === "equipment"
  );

  const japaneseEquipments = publishedEquipments.filter(
    (row) => !row._original_post || row._locale === "ja"
  );
  const englishEquipmentsMap = new Map<string, CsvRow>(
    publishedEquipments
      .filter((row) => row._locale === "en_US" && row._original_post)
      .map((row) => [row._original_post, row])
  );

  const sqlStatements: string[] = [];
  sqlStatements.push("-- Generated by TypeScript Script for Equipments\n");
  sqlStatements.push("-- Languages table pre-populated as per schema");
  sqlStatements.push(
    "INSERT OR IGNORE INTO languages (code, name, is_default) VALUES ('en', 'English', FALSE), ('ja', 'Japanese', TRUE);\n"
  );

  // 1. Process a single Category for all Equipments
  console.log("Processing categories...");
  const EQUIPMENT_CATEGORY_ID = 200; // Using a high number to avoid clashes
  const jaCategoryName = "設備";
  const enCategoryName = "Equipment";

  sqlStatements.push("-- Inserting a single Category for all Equipments");
  const equipmentCategory: Category = {
    id: EQUIPMENT_CATEGORY_ID,
    type: "equipments",
  };
  sqlStatements.push(
    `INSERT INTO categories (id, type) VALUES (${
      equipmentCategory.id
    }, ${escapeSqlString(equipmentCategory.type)});`
  );

  const jaCatTranslation: CategoryTranslation = {
    category_id: EQUIPMENT_CATEGORY_ID,
    language_code: "ja",
    category_name: jaCategoryName,
  };
  sqlStatements.push(
    `INSERT INTO category_translations (category_id, language_code, category_name) VALUES (${
      jaCatTranslation.category_id
    }, ${escapeSqlString(jaCatTranslation.language_code)}, ${escapeSqlString(
      jaCatTranslation.category_name
    )});`
  );

  const enCatTranslation: CategoryTranslation = {
    category_id: EQUIPMENT_CATEGORY_ID,
    language_code: "en",
    category_name: enCategoryName,
  };
  sqlStatements.push(
    `INSERT INTO category_translations (category_id, language_code, category_name) VALUES (${
      enCatTranslation.category_id
    }, ${escapeSqlString(enCatTranslation.language_code)}, ${escapeSqlString(
      enCatTranslation.category_name
    )});`
  );
  sqlStatements.push("\n-- End of Categories\n");

  // 2. Process Posts and Translations
  console.log("Processing equipment posts and translations...");
  sqlStatements.push("-- Inserting Equipment Posts and Post Translations");
  for (const jaEquipment of japaneseEquipments) {
    const postId = parseInt(jaEquipment.ID, 10);
    if (isNaN(postId)) continue;

    // Create the main post entry
    const post: Post = {
      id: postId,
      type: "equipments",
      category: jaCategoryName, // Use the Japanese category name
      thumbnail: getThumbnailUrl(jaEquipment["Image URL"]),
    };
    sqlStatements.push(
      `INSERT INTO posts (id, type, category, thumbnail) VALUES (${
        post.id
      }, ${escapeSqlString(post.type)}, ${escapeSqlString(
        post.category
      )}, ${escapeSqlString(post.thumbnail)});`
    );

    // Create Japanese translation
    const jaTranslation: PostTranslation = {
      post_id: postId,
      language_code: "ja",
      title: jaEquipment.Title,
      cardDescription: createCardDescription(jaEquipment.Content),
      sections: [{ type: "html", content: jaEquipment.Content }],
    };
    sqlStatements.push(
      `INSERT INTO post_translations (post_id, language_code, title, cardDescription, sections) VALUES (${
        jaTranslation.post_id
      }, ${escapeSqlString(jaTranslation.language_code)}, ${escapeSqlString(
        jaTranslation.title
      )}, ${escapeSqlString(jaTranslation.cardDescription)}, ${escapeSqlString(
        JSON.stringify(jaTranslation.sections)
      )});`
    );

    // Check for and create English translation
    const enEquipment = englishEquipmentsMap.get(jaEquipment.ID);
    if (enEquipment) {
      const enTranslation: PostTranslation = {
        post_id: postId,
        language_code: "en",
        title: enEquipment.Title,
        cardDescription: createCardDescription(enEquipment.Content),
        sections: [{ type: "html", content: enEquipment.Content }],
      };
      sqlStatements.push(
        `INSERT INTO post_translations (post_id, language_code, title, cardDescription, sections) VALUES (${
          enTranslation.post_id
        }, ${escapeSqlString(enTranslation.language_code)}, ${escapeSqlString(
          enTranslation.title
        )}, ${escapeSqlString(
          enTranslation.cardDescription
        )}, ${escapeSqlString(JSON.stringify(enTranslation.sections))});\n`
      );
    } else {
      sqlStatements.push("\n");
    }
  }
  sqlStatements.push("\n-- End of Equipment Posts\n");

  // 3. Write to SQL file
  const outputFilePath = path.join(__dirname, "insert_equipments.sql");
  fs.writeFileSync(outputFilePath, sqlStatements.join("\n"));

  console.log(
    `Successfully generated SQL script for equipments at: ${outputFilePath}`
  );
};

// Execute the script
generateEquipmentSqlScript();
